# Site settings
title: RefrainPlain
subtitle: "Adventures in nature, travel, and photography."
email: refrain_plain@jaiminbhatt.com
description: >-
  A blog dedicated to nature lovers, travel enthusiasts, and photography fans.
  Explore breathtaking journeys, stunning landscapes, and tips to capture the
  beauty of our world.
lang: en-US
baseurl: ""
domain: "jaiminbhatt7.github.io"
url: "https://jaiminbhatt7.github.io"

# Theme
remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

# Favicon
favicon: /assets/images/favicon.png

# Accent color
accent_color: '#2d72d9'

# Site navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/

# Footer
footer:
  content: "&copy; Jaimin. All rights reserved."
  has_social: true

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Permalink
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
